// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ9mQu7i-RGk1ktxgWkhjMTgb7FSFBJ7k',
    appId: '1:864140492580:web:47279933cdae4358443db1',
    messagingSenderId: '864140492580',
    projectId: 'jassem-notes-flutter',
    authDomain: 'jassem-notes-flutter.firebaseapp.com',
    storageBucket: 'jassem-notes-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0WntyI41ze6jqJMKR2JDVFx-C6kE8sXY',
    appId: '1:864140492580:android:e4656c8c60582a74443db1',
    messagingSenderId: '864140492580',
    projectId: 'jassem-notes-flutter',
    storageBucket: 'jassem-notes-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbLXBcLncJcbsX8SqcDcZNpsDlsnLuMr0',
    appId: '1:864140492580:ios:24e044cb5e281149443db1',
    messagingSenderId: '864140492580',
    projectId: 'jassem-notes-flutter',
    storageBucket: 'jassem-notes-flutter.appspot.com',
    iosClientId: '864140492580-ih7bqh0r07d86iiktgj8q7md9u8v1akt.apps.googleusercontent.com',
    iosBundleId: 'com.jassem.mynotes',
  );
}
